### PR TITLE
Update version.gradle

### PR DESCRIPTION
**Pull request by KarrePrakash**

### CODE REVIEW

**Comment by PHELAT** [comment]
Thank you for your contribution on this project. I'm going to release this today.

**Comment by KarrePrakash** [comment]
How do I get the latest changes in gradle dependency

**Comment by KarrePrakash** [comment]
> Thank you for your contribution on this project. I'm going to release this today.

OK Thank you

**Comment by PHELAT** [comment]
> How do I get the latest changes in gradle dependency

Your change is now available in the latest release(1.0.1).

**Pull request merged**
